### ISSUE TITLE
Could you add Overdrive/Libby too

### ISSUE THREAD

**Issue by Amraan-Amjad** [jo1gi/grawlix#9]
Heyy @jo1gi 
Could you add Overdrive/Libby like in https://github.com/jo1gi/audiobook-dl
It could be very helpful

**Comment by jo1gi** [comment]
It doesn't make much sense to add it, since they are already available as acsm files. Just download the acsm file and download and decrypt it with a tool that supports acsm files.

Fx:
- [deDRM Calibre Plugin](https://github.com/noDRM/DeDRM_tools)
- [knock](https://web.archive.org/web/20221016154220/https://github.com/BentonEdmondson/knock)
- [naerao](https://gitlab.com/naerao/naerao)
- [acsmconverter.com](https://acsmconverter.com)

**Comment by Amraan-Amjad** [comment]
Okay
